# Generated by Django 2.0.8 on 2018-11-25 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readersclub', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
