# Generated by Django 2.0.8 on 2018-12-13 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readersclub', '0004_auto_20181213_0116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['review_id']},
        ),
    ]
