# Generated by Django 2.0.8 on 2018-12-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readersclub', '0005_auto_20181213_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='pseudonym',
            field=models.CharField(default='', max_length=200),
        ),
    ]
