# Generated by Django 2.0.8 on 2018-12-14 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readersclub', '0008_review_vote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name']},
        ),
    ]
