# Generated by Django 2.1.2 on 2018-12-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readersclub', '0009_auto_20181214_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='awards',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
